export const ENV = {
  appId: process.env.VITE_APP_ID ?? (process.env.NODE_ENV === "production" ? "" : "local-sql-assistant"),
  cookieSecret: process.env.JWT_SECRET ?? (process.env.NODE_ENV === "production" ? "" : "local-development-secret-change-in-production"),
  databaseUrl: process.env.DATABASE_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  ollamaBaseUrl: process.env.OLLAMA_BASE_URL ?? "http://localhost:11434",
  llmModel: process.env.OLLAMA_MODEL ?? "qwen2.5-coder:1.5b",
  ollamaMaxTokens: Number(process.env.OLLAMA_MAX_TOKENS ?? 512),
  ollamaTimeoutMs: Number(process.env.OLLAMA_TIMEOUT_MS ?? 120_000),
  ollamaAuxiliaryAi: process.env.OLLAMA_AUXILIARY_AI === "true",
  targetDatabaseUrl: process.env.TARGET_DATABASE_URL ?? "",
};
